### ISSUE TITLE
LUA Mod menu broken due to mod

### ISSUE THREAD

**Issue by Jestersage** [funknapkin/PD2-Blacklist#1]
A quick test of the "Lua Mod options" shows that somehow your mod removed any options not just for this mod, but also other mods, from Goonmod to Gagehud and etc.

**Comment by funknapkin** [comment]
I installed Goonmod and Gagehud on my end, along with this mod, and could not replicate your issue. Could you provide more information on your setup and what you're doing to encounter this issue?

**Comment by Jestersage** [comment]
Just realize it's actually under "mod option" and not "Lua mod"

With only BLT, Oh-no skillset mod, and yours:
http://steamcommunity.com/sharedfiles/filedetails/?id=505309209
Mod options: http://steamcommunity.com/sharedfiles/filedetails/?id=505309241

With your mod disabled, and everythign else enabled:
http://steamcommunity.com/sharedfiles/filedetails/?id=505309260
http://steamcommunity.com/sharedfiles/filedetails/?id=505309274

**Comment by funknapkin** [comment]
~~I've used your exact setup (Blacklist + Oh No! More Skillsets) and still can't encounter the issue on my end. That's annoying to debug.~~

From what I can see in your screenshots though, it feels like my mod doesn't initialize properly. This would explain why it doesn't add an entry in the Mod Options menu. This could also explain why it removes entries from the other mods: if it encounters en error, BLT might not handle it properly and delete the menus.

~~In any case, in order to debug this I'll need some log files. Please follow these steps, and I'll look into them:~~
1. ~~Enable all your mods, including Blacklist, and exit the game~~
2. ~~Go in your logs folder and remove/rename the latest log file. We don't need it, but it doesn't hurt to keep it. (The log folder is typically C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\mods\logs)~~
3. ~~Start the game, go in the Mod Options menu, and exit~~
4. ~~Upload the latest log file and link it here.~~

I found the issue: I deleted my config files and encounted the issue. It shouldn't be hard to fix, since it doesn't seem to depend on other mods.

**Comment by MaculaGameplay** [comment]
Great.

**Comment by funknapkin** [comment]
This bug should be fixed now.
